name: Lint and Format

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  lint-and-format:
    name: Lint and Format Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      # Install specific ESLint version that works with Next.js config format
      - name: Install compatible ESLint
        run: npm install --save-dev eslint@8.56.0
      
      # Run Next.js built-in linting
      - name: Run Next.js lint
        run: npm run lint
      
      # Run Next.js lint with --fix flag to automatically fix issues
      - name: Fix linting issues
        run: npm run lint -- --fix
        continue-on-error: true
      
      # Run Prettier to format files
      - name: Install Prettier
        run: npm install --save-dev prettier
        
      - name: Format code with Prettier
        run: npx prettier --write "**/*.{js,jsx,ts,tsx,css,scss,json,md}"
        continue-on-error: true
      
      # Commit and push formatting changes if any
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: auto-format code"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
          file_pattern: "**/*.{js,jsx,ts,tsx,css,scss,json,md}"
          # Only run on push to branches, not on PRs
          branch: ${{ github.head_ref || github.ref_name }}
        if: github.event_name == 'push'